import os
from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.S')
path = [os.path.join(cwd, '..', '..', 'backtrace')]

group = DefineGroup('BacktraceArch', src,
                    depend = ['RT_USING_STACK_BACKTRACE'], CPPPATH = path)

Return('group')
