from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
path = [cwd]

if GetDepend('FINSH_USING_MSH'):
    src += Glob('testcases/*.c')

group = DefineGroup('Backtrace', src,
                    depend = ['RT_USING_STACK_BACKTRACE'], CPPPATH = path)

Return('group')
